Dev param reorg
NOAA-OWP/noah-mp-modular pull request #13
Opened 2021-09-07 18:59 UTC by nmizukami

- Split namelist (commit e7d2af6b7fb16c375bdb9fec3f58728e0df1a963)
  previous - `namelist.input` includes model configurations, initialization and parameters 
  update - `param.namelist` includes model parameters and `namelist.input` includes model configurations, initialization.

- Split namelist reading routine (commit 41adfcc342f134b24a510d6055b73eff7026060d)
  Based on the namelist split, the namelist reading routine needs to be split into two - ParametersRead.f90 and 
  modelConfigRead.f90

- Other changes based on new namelist routines (commit eee05fb39f7f45a2c4df73dedb281a2397751624 and ccf44cc59808e7ba75816bc7483140df41889c50)
  Various type.f90 files and Makefiles

2021-09-07 19:16 UTC, andywood reviewed
Hi Naoki, I think this is a good first step, and separates parameters from other model options & settings.  Ideally, though, we want to get back to reading the standard noah-mp TABLES (eg VEGPARM.TBL, GENPARM.TBL, MPTABLE.TBL etc), so that we can easily leverage upgrades in parameters by the noah-mp community.  So instead of a namelist parameter read, we implement the something resembling HRLDAS parameter read.  Having two namelists for the code may be a bit confusing.

2021-09-07 19:17 UTC, andywood commented
I can merge this now if it runs, so that the PR doesn't get too big.

2021-09-07 19:28 UTC, nmizukami commented
Yes, I remember this conversation (using *.TBL). I will look into this. I tested this and get identical result with the original one (just used nccmp)

2021-09-07 20:36 UTC, SnowHydrology commented
> I can merge this now if it runs, so that the PR doesn't get too big.

@andywood, please don't merge as I'd like to take a deeper look tomorrow at some of the things that stood out to me. Thanks for getting this started, @nmizukami!

2021-09-07 21:23 UTC, andywood commented
Hi Keith,

Sorry, by 'now' I meant 'after Keith looks it over too'.  I mainly meant
that I think this gets us halfway where we want to be -- but if it's
usable, I can merge it so that the next part doesn't turn this into a
massive PR.  Also, quick note, the merge is from Naoki's fork branch into
the OWP branch on param reads, not into master.

-Andy


On Tue, Sep 7, 2021 at 2:36 PM K. Jennings ***@***.***> wrote:

> I can merge this now if it runs, so that the PR doesn't get too big.
>
> @andywood <https://github.com/andywood>, please don't merge as I'd like
> to take a deeper look tomorrow at some of the things that stood out to me.
> Thanks for getting this started, @nmizukami <https://github.com/nmizukami>
> !
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-OWP/noah-mp-modular/pull/13#issuecomment-914613388>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABIKARO5VGU4G5I6GB2UTO3UAZZURANCNFSM5DS73TOA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-08 12:45 UTC, SnowHydrology requested changes
Let's address some of the comments before merging. Thanks for the great work, @nmizukami!

2021-09-08 12:45 UTC, SnowHydrology commented on modules/full/driver/noahmp_driver.f90
> +  use modelConfigRead
Is there a strong motivation to change from `NamelistRead` to `modelConfigRead`? I noticed in the code below that we still use the `namelist_type`, so this may introduce unnecessary confusion. If we choose the latter name, I would prefer it just say `ConfigRead`.

2021-09-08 12:45 UTC, SnowHydrology commented on modules/full/driver/noahmp_driver.f90
> +  call paramNML%ReadNamelist(param_nml_file)
These two calls use different syntax for the same operation. `namelist%ReadNamelist()` gets the file name from `modelConfigRead`, whereas `paramNML%ReadNamelist(param_nml_file)` gets the file name from the driver. I have little preference, but I'd like them to be consistent.

2021-09-08 12:45 UTC, SnowHydrology commented on modules/full/driver/noahmp_driver.f90
> +  type (parametersNML)     :: paramNML
Does NML here stand for namelist? It seems like we're introducing unnecessary uncertainty by calling the params file a namelist and having two parameters types.

2021-09-08 12:45 UTC, SnowHydrology commented on modules/full/parameters/param.namelist
> +&soil_parameters
I agree with @andywood that we should not call this a namelist and that the params should be split out into their respective tables if we want to go from leaving everything in the namelist as we currently do to using a method that's more consistent with the HRLDAS version of Noah-MP.

2021-09-08 12:45 UTC, SnowHydrology commented on modules/full/run/namelist.input
> + parameters_nml = ./parameters/param.namelist
This is also in the driver. Does it serve an additional purpose here?

2021-09-08 12:45 UTC, SnowHydrology commented on modules/full/src/DomainType.f90
> +    type(modelConfig_type) :: namelist
To echo my earlier comment, I don't think introducing a new type (`modelConfig_type`) just to rename it to `namelist` is the way to go here.

2021-09-08 14:31 UTC, andywood commented on modules/full/driver/noahmp_driver.f90
> +  use modelConfigRead
I'd call it ParamRead, since the configuration is largely set by the namelist.  Again, avoid confusion since other models' control files are referred to as config.  This is a parameter reading routine.

2021-09-08 14:33 UTC, andywood commented on modules/full/driver/noahmp_driver.f90
> +  type (parametersNML)     :: paramNML
agree.  there should be no confusion between read namelist (the config) and read params.

2021-09-08 14:34 UTC, andywood commented on modules/full/run/namelist.input
> + parameters_nml = ./parameters/param.namelist
I think of the driver assignments should eventually get moved to other source files, keeping the driver clean.

2021-09-08 17:19 UTC, andywood commented
Sounds good, Naoki.  I also don't think the namelist should contain initial
state values -- that would be part of a readState function & file set.
Ideally the namelist would include:
* major filenames / paths
* time control settings (start/stop/timestep)
* space control settings (eg subdomain)
* physics options
* maybe output options (eg frequency)

On Wed, Sep 8, 2021 at 11:10 AM Naoki Mizukami ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In modules/full/driver/noahmp_driver.f90
> <https://github.com/NOAA-OWP/noah-mp-modular/pull/13#discussion_r704551488>
> :
>
> > @@ -8,7 +8,8 @@ program noahmp_driver
>    use NoahMPOutput
>    use LevelsType
>    use DomainType
> -  use NamelistRead
> +  use modelConfigRead
>
> some small motivation was to make it a little more descriptive (general
> terminology to something specific). now model parameters are out, so
> namelist include mostly model configurations (maybe initial condition could
> be separated later? @andywood <https://github.com/andywood>? ). So Keith,
> the problem here is I still call namelist to create the variable with type
> (modelConfig_type) in many f90 files
> ------------------------------
>
> In modules/full/driver/noahmp_driver.f90
> <https://github.com/NOAA-OWP/noah-mp-modular/pull/13#discussion_r704555354>
> :
>
> >
>  !---------------------------------------------------------------------
>  !  initialize
>  !---------------------------------------------------------------------
>
>    call namelist%ReadNamelist()
> +  call paramNML%ReadNamelist(param_nml_file)
>
> Based on discussion with Andy ***@***.*** <https://github.com/andywood>),
> decided to let a user specify where parameter file(s) are, and what are the
> names. Could do the same thing for configuration file (now hard-coded).
> ------------------------------
>
> In modules/full/parameters/param.namelist
> <https://github.com/NOAA-OWP/noah-mp-modular/pull/13#discussion_r704562814>
> :
>
> > @@ -0,0 +1,161 @@
> +&soil_parameters
>
> This will be replaced by original noah-mp tables. I can call this
> parameters_file or something
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-OWP/noah-mp-modular/pull/13#discussion_r704551488>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABIKARM6V2X2X44N7QQUJNTUA6KGRANCNFSM5DS73TOA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-08 21:02 UTC, nmizukami commented
@SnowHydrology and @andywood please take a look.   I cleaned up (remove parameterRead.f90) and put paramRead under parameter type data structure.

2021-09-08 21:04 UTC, nmizukami commented
I accidentally removed tailing spaces (my vim editor setting for fortran code and Makefile etc.)

2021-09-09 21:46 UTC, andywood commented
merging this PR for now.  there may be small things left we can clean up but let's keep those commits for the next PR.

2021-09-09 21:46 UTC, merged